Feat/fcm initial
vote4hk/vote4hk-mobile pull request #7
Opened 2020-08-02 16:46 UTC by khmak3

Please download google-services.json from below url and put into android/app/ for all firebase keys
https://console.firebase.google.com/u/0/project/vote4hk/settings/general/android:com.example.vote4hk_mobile

Please goto below URL to adjust any API restriction. Firebase done a bad job for the auto adjustment
https://console.cloud.google.com/apis/credentials?project=vote4hk

2020-08-02 16:48 UTC, khmak3 commented
You can go to https://console.firebase.google.com/u/0/project/vote4hk/notification to use a sample cloud message to send a notification to client

2020-08-03 12:57 UTC, nandiheath requested changes

2020-08-03 12:57 UTC, nandiheath commented on lib/services/user_service.dart
> +      String _userID = _sharedPreferences.getString('userID');
only private variable should prefix underline

2020-08-03 12:57 UTC, nandiheath commented on lib/services/user_service.dart
> +class UserService {
i would prefer abstracting this class. e.g. `FirebaseUserService` implements `UserService` and we have kind of factory method for easily switch from firebase to other datastore.

2020-08-03 12:57 UTC, nandiheath commented on lib/services/user_service.dart
> +  Future<void> checkIsSignedIn(String _userID) async {
i suggest params should have no `_` prefix.

2020-08-03 12:57 UTC, nandiheath commented on lib/services/user_service.dart
> +    String userID = _userID;
this is not necessary?

2020-08-07 16:34 UTC, closed without merging